name: Lint

on: [push, pull_request]

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run Black
      uses: rickstaa/action-black@v1
      with:
        black_args: "."
        fail_on_error: true
    - name: Push changes
      if: ${{ steps.black.outputs.changes == 'true' }}
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        git remote set-url origin https://x-access-token:${{ secrets.ACTIONS_PAT }}@github.com/${{ github.repository }}
        git add .
        git commit -m "Format Python code with psf/black"
        git push origin actions/black
